server:
  port: 8095

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/leonelrh/config
          username: wilmerleonel1717@gmail.com
          password: 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
          default-label: master
  application:
    name: config-server-service
